spring.application.name=user

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

user.association=COMMUNITY

rabbitmq.queue.energy=energy.queue
