spring.application.name=restapi
server.port=8080

spring.mvc.log-request-details=true
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5442/energy
spring.datasource.username=disysuser
spring.datasource.password=disyspw
