spring.application.name=producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

producer.association=COMMUNITY
producer.weather-url=https://api.open-meteo.com/v1/forecast?latitude=48.2082&longitude=16.3738&current=cloud_cover,is_day&timezone=Europe%2FVienna

rabbitmq.queue.energy=energy.queue
